var all_roles_base = {
	"Adze": {limit: 1, faction_leader: true, tg_vamp_overhaul: true, category: "Vampire Killing"},
	"Agent": {limit: 6, tg_ar: true, category: "Mafia Deception"},
	"Ambusher": {limit: 1, category: "Mafia Killing"},
	"Amnesiac": {limit: 6, category: "Neutral Benign"},
	"Arsonist": {limit: 6, category: "Neutral Killing"},
	"Blackmailer": {limit: 6, category: "Mafia Support"},
	"Bodyguard": {limit: 6, category: "Town Protective"},
	"Bouncer": {limit: 6, tg_ar: true, category: "Town Protective"},
	"Catacano": {limit: 1, tg_vamp_overhaul: true, category: "Vampire Conversion"},
	"Conquerer": {limit: 1, tg_ar: true, category: "Neutral Chaos"},
	"Consigliere": {limit: 6, category: "Mafia Support"},
	"Consort": {limit: 6, category: "Mafia Support"},
	"Coven Leader": {limit: 1, coven: true, category: "Coven Evil"},
	"Crusader": {limit: 6, coven: true, category: "Town Protective"},
	"Disguiser": {limit: 6, category: "Mafia Deception"},
	"Doctor": {limit: 6, category: "Town Protective"},
	"Escort": {limit: 6, category: "Town Support"},
	"Executioner": {limit: 6, category: "Neutral Evil"},
	"Forger": {limit: 6, category: "Mafia Deception"},
	"Framer": {limit: 6, category: "Mafia Deception"},
	"Gierach": {limit: 6, tg_vamp_overhaul: true, category: "Vampire Support"},
	"Godfather": {limit: 1, faction_leader: true, category: "Mafia Killing"},
	"Guardian Angel": {limit: 6, coven: true, category: "Neutral Benign"},
	"Hex Master": {limit: 1, coven: true, category: "Coven Evil"},
	"Huntsman": {limit: 6, tg_ar: true, category: "Neutral Chaos"},
	"Hypnotist": {limit: 6, category: "Mafia Deception"},
	"Investigator": {limit: 6, category: "Town Investigative"},
	"Jailor": {limit: 1, category: "Random Town"},
	"Janitor": {limit: 6, category: "Mafia Deception"},
	"Jester": {limit: 6, category: "Neutral Evil"},
	"Judge": {limit: 1, tg_ar: true, category: "Town Support"},
	"Juggernaut": {limit: 1, coven: true, category: "Neutral Killing"},
	"Lookout": {limit: 6, category: "Town Investigative"},
	"Mafioso": {limit: 1, faction_leader: true, category: "Mafia Killing"},
	"Mayor": {limit: 1, category: "Town Support"},
	"Medium": {limit: 6, category: "Town Support"},
	"Medusa": {limit: 1, coven: true, category: "Coven Evil"},
	"Mystic": {limit: 1, tg_ar: true, category: "Coven Evil"},
	"Necromancer": {limit: 1, coven: true, category: "Coven Evil"},
	"Nelapsi": {limit: 6, tg_vamp_overhaul: true, category: "Vampire Manipulation"},
	"Occultist": {limit: 6, tg_vamp_overhaul: true, category: "Town Investigative"},
	"Patient": {limit: 1, tg_ar: true, category: "Neutral Killing"},
	"Pirate": {limit: 1, coven: true, category: "Neutral Chaos"},
	"Plaguebearer": {limit: 1, coven: true, category: "Neutral Chaos"},
	"Poisoner": {limit: 1, coven: true, category: "Coven Evil"},
	"Potion Master": {limit: 1, coven: true, category: "Coven Evil"},
	"Psychic": {limit: 6, coven: true, category: "Town Investigative"},
	"Recon": {limit: 6, tg_ar: true, category: "Mafia Support"},
	"Retributionist": {limit: 1, category: "Town Support"},
	"Rolestopper": {limit: 6, tg_ar: true, category: "Neutral Evil"},
	"Serial Killer": {limit: 6, category: "Neutral Killing"},
	"Servant": {limit: 6, tg_ar: true, category: "Neutral Benign"},
	"Sheriff": {limit: 6, category: "Town Investigative"},
	"Spy": {limit: 6, category: "Town Investigative"},
	"Survivor": {limit: 6, category: "Neutral Benign"},
	"Talamaur": {limit: 6, tg_vamp_overhaul: true, category: "Vampire Support"},
	"Technician": {limit: 6, tg_ar: true, category: "Mafia Support"},
	"Tracker": {limit: 6, coven: true, category: "Town Investigative"},
	"Transporter": {limit: 6, category: "Town Support"},
	"Trapper": {limit: 6, coven: true, category: "Town Protective"},
	"Veteran": {limit: 1, category: "Town Killing"},
	"Vigilante": {limit: 6, category: "Town Killing"},
	"Werewolf": {limit: 1, category: "Neutral Killing"},
	"Witch": {limit: 6, coven: false, category: "Neutral Evil"},
};
