var all_roles = {
	"Ambusher": {limit: 1},
	"Amnesiac": {limit: 6},
	"Arsonist": {limit: 6},
	"Blackmailer": {limit: 6},
	"Bodyguard": {limit: 6},
	"Consigliere": {limit: 6},
	"Consort": {limit: 6},
	"Coven Leader": {limit: 1, coven: true},
	"Crusader": {limit: 6, coven: true},
	"Disguiser": {limit: 6},
	"Doctor": {limit: 6},
	"Escort": {limit: 6},
	"Executioner": {limit: 6},
	"Forger": {limit: 6},
	"Framer": {limit: 6},
	"Godfather": {limit: 1, mafia_leader: true},
	"Guardian Angel": {limit: 6, coven: true},
	"Hex Master": {limit: 1, coven: true},
	"Hypnotist": {limit: 6},
	"Investigator": {limit: 6},
	"Jailor": {limit: 1},
	"Janitor": {limit: 6},
	"Jester": {limit: 6},
	"Juggernaut": {limit: 1, coven: true},
	"Lookout": {limit: 6},
	"Mafia Roles": {limit: 6},
	"Mafioso": {limit: 1, mafia_leader: true},
	"Mayor": {limit: 1},
	"Medium": {limit: 6},
	"Medusa": {limit: 1, coven: true},
	"Necromancer": {limit: 1, coven: true},
	"Neutral Roles": {limit: 6},
	"Pestilence": {limit: 1, coven: true},
	"Pirate": {limit: 1, coven: true},
	"Plaguebearer": {limit: 1, coven: true},
	"Poisoner": {limit: 1, coven: true},
	"Potion Master": {limit: 1, coven: true},
	"Psychic": {limit: 6, coven: true},
	"Retributionist": {limit: 1},
	"Serial Killer": {limit: 6},
	"Sheriff": {limit: 6},
	"Spy": {limit: 6},
	"Survivor": {limit: 6},
	"Town Roles": {limit: 6},
	"Tracker": {limit: 6, coven: true},
	"Transporter": {limit: 6},
	"Trapper": {limit: 6, coven: true},
	"Vampire": {limit: 6},
	"Vampire Hunter": {limit: 6},
	"Veteran": {limit: 1},
	"Vigilante": {limit: 6},
	"Werewolf": {limit: 1},
	"Witch": {limit: 6, coven: false},
	"Charmer": {limit: 6, test_role: true, category: "Town Protective"},
	"Conqueror": {limit: 1, test_role: true, category: "Neutral Chaos"},
	"Mortician": {limit: 1, test_role: true, category: "Neutral Chaos"},
	"Blacksmith": {limit: 6, test_role: true, category: "Town Protective"},
	"Duelist": {limit: 6, test_role: true, category: "Town Protective"},
	"Associate": {limit: 1, test_role: true, category: "Mafia Support"},
	"Confounder": {limit: 6, test_role: true, category: "Mafia Support"},
	"Historian": {limit: 6, test_role: true, category: "Town Investigative"},
	"Spellslinger": {limit: 1, coven: true, test_role: true, category: "Coven Evil"},
	"Caporegime": {limit: 1, test_role: true, category: "Mafia Support"},
	"Mystic": {limit: 1, coven: true, test_role: true, category: "Coven Evil"},
	"Hitman": {limit: 1, test_role: true, category: "Mafia Killing"},
	"Kleptomaniac": {limit: 6, test_role: true, category: "Neutral Evil"},
	"Gossip": {limit: 6, test_role: true, category: "Town Investigative"},
	"Rolestopper": {limit: 6, test_role: true, category: "Neutral Evil"},
	"Coroner": {limit: 6, test_role: true, category: "Town Investigative"},
	"Agent": {limit: 6, test_role: true, category: "Mafia Deception"},
	"Ritualist": {limit: 1, coven: true, test_role: true, category: "Coven Evil"},
	"Servant": {limit: 6, test_role: true, category: "Neutral Benign"},
};
